apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.20
    helm:
      values: |
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::795689218805:role/external-secrets"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
