apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.9.1
    helm:
      values: |
        provider:
          packages:
          - crossplane/provider-aws:v0.32.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
