apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
      argocd.argoproj.io/sync-wave: "5"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds


