---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.16.11
    chart: linkerd-control-plane
    helm:
      values: |
        identity:
          issuer:
            scheme: kubernetes.io/tls
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjTCCATSgAwIBAgIRALV372CZpNah47NUi6whwu0wCgYIKoZIzj0EAwIwJTEj
          MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjQwNzIzMjI0
          MTQ0WhcNMzQwNjE0MTA0MTQ0WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
          c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIC6YI3uvhuWDtL0
          ePdK9oP5UriSdgI7G1lbhYN5LxgfBCsaarfYip1iUomLC3zlt8lRWxqB7mX5OZh0
          1slk7nGjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
          A1UdDgQWBBQpEdhTuyE8+H5cd4qkdGToeWkF8zAKBggqhkjOPQQDAgNHADBEAiBm
          daJs+F0maose9Qnmr+jHae9a04Chyi2wgovu34cWIAIgD4zp/4CU669qjQtfqbf3
          hRDnUDoBSRYIULT9izuNOhw=
          -----END CERTIFICATE-----

        
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  revisionHistoryLimit: 10
