---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  refreshInterval: 1h     
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: linkerd-trust-anchor
    creationPolicy: Owner
  dataFrom:
  - extract:
      decodingStrategy: Base64
      key: stage/linkerd/trust-anchor
    rewrite:
    - regexp:
        source: ca.crt
        target: tls.crt
    - regexp:
        source: ca.key
        target: tls.key
    - regexp:
        source: ca.crt
        target: tls.crt
    - regexp:
        source: ca.key
        target: ca.key
